apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap1-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cap1
  template:
    metadata:
      labels:
        app: cap1
    spec:
      containers:
        - name: cap1-container
          image: kunal1010/cap1
          ports:
            - containerPort: 80
